name: itea-weather-station

services:
  weather-edge-processor:
    build:
      context: ./data-processor
      dockerfile: Dockerfile
    container_name: weather-edge-processor
    environment:
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_URL: ${INFLUXDB_ROUTE}
      DATA_LOCATION: ${DATA_LOCATION}
      MEASUREMENT_NAME: ${MEASUREMENT_NAME}
      BROKER_ENDPOINT: ${BROKER_ENDPOINT}
      BROKER_USERNAME: ${SUB_USERNAME}
      BROKER_PASSWORD: ${MQTT_PASSWORD}
      BROKER_PORT: ${MQTT_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}
    restart: unless-stopped
    networks:
      - weather-network

  database:
    env_file:
      - .env
    image: influxdb:2
    container_name: weatherdb
    ports:
      - "8086:8086"
    volumes: 
      - ./influxdb2-data:/var/lib/influxdb2
      - ./influxdb2-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
    restart: unless-stopped
    networks:
      - weather-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default websocket port
    volumes:
      - ./mosquitto-config:/mosquitto/config
      - ./mosquitto-init:/mosquitto-init
    entrypoint: ["/mosquitto-init/entrypoint.sh"]
    networks:
      - weather-network
    restart: "no"
    stdin_open: true
    tty: true

  itea-edge-hub:
    env_file:
      - .env
    image: pancakeslmao/itea-edge-hub:1.1
    container_name: itea-edge-hub
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/weather-edge-hub/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_ROLE: ${ADMIN_ROLE}
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_NAME: ${TEST_NAME}
      TEST_PASSWORD_HASH: ${TEST_PASSWORD_HASH}
      TEST_EMAIL: ${TEST_EMAIL}
      TEST_ROLE: ${TEST_ROLE}
      INFLUXDB_ROUTE: ${INFLUXDB_ROUTE}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    depends_on:
      - database
    networks:
      - weather-network
    restart: unless-stopped

networks:
  weather-network:
    driver: bridge

volumes:
  influxdb2-data:
  influxdb2-config:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log: